// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef ui_fluid_h
#define ui_fluid_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *calcwin;
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Group.H>
extern Fl_Group *general_grp;
#include <FL/Fl_Button.H>
extern Fl_Button *memory_recall;
#include <FL/Fl_Box.H>
extern Fl_Box *value_display;
extern Fl_Group *binary_view;
extern Fl_Group *scientific_grp;
extern Fl_Box *paren_view_sci;
#include <FL/Fl_Round_Button.H>
extern Fl_Group *programmer_grp;
extern Fl_Box *paren_view_prg;
Fl_Double_Window* make_window();
extern Fl_Menu_Item menu_[];
#endif
